on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

name: CI

jobs:
  x86_64-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: newam
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check -L
